dataset:
  root: 'datasets/historical_wi'
  batch_size: 128
  num_workers: 0
  prefetch_factor: 2
extract:
  weights: ''
  window_size: 224
  train_stride: 224
  test_stride: 56
  compile_mode: 'max-autotune-no-cudagraphs'
  compile_backend: 'inductor'
codebook:
  samples_per_document: 512
  codebook_iterations: 250
  codebook_clusters: 100
  pca_dimensions: 384
evaluation:
  metrics:
  - topk:1
  - topk:5
  - topk:10
  - mAP
  - mAP:5
  - mAP:10